apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-data
  labels:
    app : smartm2m
spec:
  storageClassName: hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/srv/app-data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-claim
  namespace: default
spec:
  storageClassName: hostpath
  volumeName: app-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
